name: pildat_cms
description: "A Flutter-based CMS application for contact management."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and functionality
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  image_picker: ^1.2.0
  intl: ^0.20.2

  # Networking
  http: ^1.5.0

  # Typeahead / Autocomplete (latest working version)
  flutter_typeahead: ^5.2.0
  google_mlkit_text_recognition: ^0.15.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
